spring:
  application:
    name: Api-GateWay
  cloud:
    gateway:
      routes:
      - id: HotelService
        uri: lb://HotelService
        predicates:
        - Path=/hotel/**
        filters:
        - AddRequestHeader=token, xyz

      - id: RatingService
        uri: lb://RatingService
        predicates:
        - Path=/rating/**

      - id: UserService
        uri: lb://UserService
        predicates:
        - Path=/users/**
server:
  port: 8084
