resilience4j:
  circuitbreaker:
    instances:
      GetUserByIdCricuitBreaker:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 10
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        minimum-number-of-calls: 2

management:
  endpoints:
    web:
      exposure:
        include: '*'

